# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{csv_schema}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jconley"]
  s.date = %q{2010-12-20}
  s.description = %q{This validator is intended to be run on csv files that are updated and received on a regular basis.  It allows you to specify required headers the following data restrictions:  columns that must be unique, columns that must be restricted to certain values, or columns that can't allow nil values.  This gem checks that the newly received file is consistent with the specified 'csv schema'.  This frees you form having to manually check that the new file has not changed and reduces the possibility that an unnoticed change will cause any subsequent analyses to be incorrect. }
  s.email = %q{}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "csv_schema.gemspec",
     "lib/csv_schema.rb",
     "spec/csv_schema_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jconley88/csv_schema}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{This gem validates the format of csv data for ETL tools}
  s.test_files = [
    "spec/csv_schema_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 1.3.1"])
      s.add_runtime_dependency(%q<fastercsv>, ["~> 1.5.3"])
    else
      s.add_dependency(%q<rspec>, ["~> 1.3.1"])
      s.add_dependency(%q<fastercsv>, ["~> 1.5.3"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 1.3.1"])
    s.add_dependency(%q<fastercsv>, ["~> 1.5.3"])
  end
end

